"""Create Productos and Marca tables

Revision ID: e767245dfa3f
Revises: 
Create Date: 2024-05-27 20:05:43.012105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e767245dfa3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cant_art', sa.INTEGER(), nullable=False))
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('cant _art')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('marca',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('precio',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('marca',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cant _art', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('cant_art')

    # ### end Alembic commands ###
